from collections.abc import Iterator

class TraceProcessorConfig:
    def __init__(self, bin_path: str | None = ..., load_timeout: int = ...) -> None: ...

class _Row:
    name: str = ...
    flat_key: str = ...
    int_value: int = ...
    min_ts: int = ...
    dur: int = ...
    track_name: str = ...
    ts: int = ...
    value: int = ...
    id: int = ...
    parent_id: int = ...
    y_axis_share_key: str = ...
    type: str = ...
    notnull: bool = ...
    pk: int = ...
    string_value: str = ...
    value_type: str = ...
    pid: int = ...
    start_ts: int = ...
    upid: int = ...
    utid: int = ...
    tid: int = ...
    severity: str = ...
    cmdline: str = ...
    description: str = ...
    pname: str = ...
    tname: str = ...
    sname: str = ...
    ctrack_id: int = ...

    def __getattr__(self, name: str) -> int: ...

class TraceProcessor:
    def __init__(self, trace: str, config: TraceProcessorConfig = ...) -> None: ...
    def query(self, sql: str) -> Iterator[_Row]: ...
    def close(self) -> None: ...
